/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calc_CONSTANTS_H
#define calc_CONSTANTS_H

namespace rpctest { namespace thrift {

class calcConstants {
 public:
  calcConstants();

};

extern const calcConstants g_calc_constants;

}} // namespace

#endif // calc_CONSTANTS_H
